# Generated by Django 5.0.6 on 2024-06-04 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingItems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='item_name',
            field=models.CharField(default='SOME STRING', max_length=100, unique=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
