# Generated by Django 5.0.6 on 2024-06-04 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingItems', '0002_item_description_item_item_name_item_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_name',
            field=models.CharField(default='SOME STRING', max_length=100),
            preserve_default=True,
        ),
    ]
