# Generated by Django 5.0.6 on 2024-06-04 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingItems', '0003_alter_item_item_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_name',
            field=models.CharField(default='SOME STRING', max_length=100, unique=True),
            preserve_default=True,
        ),
    ]
