# Generated by Django 5.0.6 on 2024-06-04 08:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingItems', '0004_alter_item_item_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
